-- MySQL Script generated by MySQL Workbench
-- Wed Jan  3 01:35:02 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema staffnetwork
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema staffnetwork
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `staffnetwork` DEFAULT CHARACTER SET utf8 ;
USE `staffnetwork` ;

-- -----------------------------------------------------
-- Table `staffnetwork`.`userType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staffnetwork`.`userType` (
  `id` VARCHAR(5) NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `staffnetwork`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staffnetwork`.`user` (
  `id` INT NOT NULL,
  `FirstName` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NULL,
  `fkuserTypeId` VARCHAR(5) NOT NULL,
  `address` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_userType1_idx` (`fkuserTypeId` ASC),
  CONSTRAINT `fk_user_userType1`
    FOREIGN KEY (`fkuserTypeId`)
    REFERENCES `staffnetwork`.`userType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `staffnetwork`.`loginInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staffnetwork`.`loginInfo` (
  `id` INT NOT NULL,
  `loginTime` DATETIME NULL,
  `logoutTime` DATETIME NULL,
  `ipAddress` VARCHAR(45) NULL,
  `browser` VARCHAR(45) NULL,
  `fkuserId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_loginInfo_user1_idx` (`fkuserId` ASC),
  CONSTRAINT `fk_loginInfo_user1`
    FOREIGN KEY (`fkuserId`)
    REFERENCES `staffnetwork`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `staffnetwork`.`loginAccess`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staffnetwork`.`loginAccess` (
  `id` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `fkuserId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_loginAccess_user_idx` (`fkuserId` ASC),
  CONSTRAINT `fk_loginAccess_user`
    FOREIGN KEY (`fkuserId`)
    REFERENCES `staffnetwork`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `staffnetwork`.`freeTime`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staffnetwork`.`freeTime` (
  `id` INT NOT NULL,
  `day` VARCHAR(10) NULL,
  `startTime` TIME NULL,
  `endTime` TIME NULL,
  `fkuserId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_freeTime_user1_idx` (`fkuserId` ASC),
  CONSTRAINT `fk_freeTime_user1`
    FOREIGN KEY (`fkuserId`)
    REFERENCES `staffnetwork`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `staffnetwork`.`jobType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staffnetwork`.`jobType` (
  `id` VARCHAR(11) NOT NULL,
  `typeName` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `staffnetwork`.`job`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staffnetwork`.`job` (
  `id` INT NOT NULL,
  `jobName` VARCHAR(25) NULL,
  `description` VARCHAR(45) NULL,
  `fkjobTypeId` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_job_jobType1_idx` (`fkjobTypeId` ASC),
  CONSTRAINT `fk_job_jobType1`
    FOREIGN KEY (`fkjobTypeId`)
    REFERENCES `staffnetwork`.`jobType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `staffnetwork`.`jobFee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staffnetwork`.`jobFee` (
  `id` INT NOT NULL,
  `jobFeeEmp` VARCHAR(45) NULL,
  `jobFeeSn` VARCHAR(45) NULL,
  `fkjobId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_jobFee_job1_idx` (`fkjobId` ASC),
  CONSTRAINT `fk_jobFee_job1`
    FOREIGN KEY (`fkjobId`)
    REFERENCES `staffnetwork`.`job` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `staffnetwork`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staffnetwork`.`post` (
  `id` INT NOT NULL,
  `description` MEDIUMTEXT NULL,
  `fkjobId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_job1_idx` (`fkjobId` ASC),
  CONSTRAINT `fk_post_job1`
    FOREIGN KEY (`fkjobId`)
    REFERENCES `staffnetwork`.`job` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `staffnetwork`.`jobTime`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staffnetwork`.`jobTime` (
  `id` INT NOT NULL,
  `startTime` DATETIME NULL,
  `endTime` DATETIME NULL,
  `fkjobId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_jobTime_job1_idx` (`fkjobId` ASC),
  CONSTRAINT `fk_jobTime_job1`
    FOREIGN KEY (`fkjobId`)
    REFERENCES `staffnetwork`.`job` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
